version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bleedthefreak
      POSTGRES_PASSWORD: bleedthefreak@ytaya
      POSTGRES_DB: pong_db